### ISSUE TITLE
Problem installing formio/formio 

### ISSUE THREAD

**Issue by qodrinzo** [formio/formio#1142]
When doing npm install; even after npm cache clean --force, and removing node_modules and package-lock.json.

Ubuntu server 18.04.5
Ram 1024 MB

Node.js versions 12.x and 14.x tried.
Formio v2.0.0-rc.31 cloned.

```
> pre-commit@1.2.2 install /opt/formio/node_modules/pre-commit
> node install.js

sh: 1: node: Permission denied

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! pre-commit@1.2.2 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR!

npm ERR! Failed at the pre-commit@1.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-18T00_09_57_071Z-debug.log
```

The **complete log** file:
```
344 warn acorn-jsx@5.3.1 requires a peer of acorn@^6.0.0 || ^7.0.0 || ^8.0.0 but none is installed. You must ins$
345 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
346 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","ar$
347 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
347 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
347 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
348 verbose stack Error: pre-commit@1.2.2 install: `node install.js`
348 verbose stack spawn ENOENT
348 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v12.19.1/lib/node_modules/npm/node_m$
348 verbose stack     at ChildProcess.emit (events.js:314:20)
348 verbose stack     at maybeClose (internal/child_process.js:1021:16)
348 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
349 verbose pkgid pre-commit@1.2.2
350 verbose cwd /opt/formio
351 verbose Linux 4.15.0-124-generic
352 verbose argv "/root/.nvm/versions/node/v12.19.1/bin/node" "/root/.nvm/versions/node/v12.19.1/bin/npm" "insta$
353 verbose node v12.19.1
354 verbose npm  v6.14.8
355 error code ELIFECYCLE
356 error syscall spawn
357 error file sh
358 error errno ENOENT
359 error pre-commit@1.2.2 install: `node install.js`
359 error spawn ENOENT
360 error Failed at the pre-commit@1.2.2 install script.
360 error This is probably not a problem with npm. There is likely additional logging output above.
361 verbose exit [ 1, true ]
```

**Comment by travist** [comment]
It is installing fine on my machine (Mac OSX). Anyone else having this issue?

**Comment by qodrinzo** [comment]
Seemingly based on my search, it was something about permissions caused by installing nvm on the root account.
