### ISSUE TITLE
Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency

### ISSUE THREAD

**Issue by qomhmd** [formio/formio#1144]
On the first "npm start", the process ceases with this error:

```
Initializing API Server.
 > Mongo connection established.
Installing...
prompt: Are you sure you wish to install? (y/N):  **(node:19855) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)**
Error: canceled
    at Interface.<anonymous> (/opt/formio/node_modules/read/lib/read.js:66:13)
    at Interface.emit (events.js:315:20)
    at Interface._ttyWrite (readline.js:875:16)
    at ReadStream.onkeypress (readline.js:213:10)
    at ReadStream.emit (events.js:315:20)
    at emitKeys (internal/readline/utils.js:345:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1144:36)
    at ReadStream.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at ReadStream.Readable.push (_stream_readable.js:223:10)
    at TTY.onStreamRead (internal/stream_base_commons.js:188:23)
canceled
```

**$ npm version**:
> {
>   formio: '2.0.0-rc.31',
>   npm: '6.14.8',
>   ares: '1.16.1',
>   brotli: '1.0.9',
>   cldr: '37.0',
>   icu: '67.1',
>   llhttp: '2.1.3',
>   modules: '83',
>   napi: '7',
>   nghttp2: '1.41.0',
>   node: '14.15.1',
>   openssl: '1.1.1g',
>   tz: '2020a',
>   unicode: '13.0',
>   uv: '1.40.0',
>   v8: '8.4.371.19-node.17',
>   zlib: '1.2.11'
> }

**Comment by travist** [comment]
Will you add --trace-warnings so we can see where this warning was added?

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
