### ISSUE TITLE
[BUG] Docker compose launch fails with "Cannot find module..."

### ISSUE THREAD

**Issue by andrewliles** [formio/formio#1295]
## Environment
Please provide as many details as you can:

- Hosting type
  - Docker, on MacOSX
- Formio.js version:
  - HEAD (=v2.2.3-rc.9) and tried v2.2.2

## Steps to Reproduce
1. Run `git clone; git@github.com:formio/formio.git; cd formio`
2. Run `docker compose up`

## Expected behavior

Running service

## Observed behavior

```
formio_1  | internal/modules/cjs/loader.js:888
formio_1  |   throw err;
formio_1  |   ^
formio_1  |
formio_1  | Error: Cannot find module 'mailgun.js'
formio_1  | Require stack:
formio_1  | - /app/src/util/util.js
formio_1  | - /app/main.js
formio_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
formio_1  |     at Function.Module._load (internal/modules/cjs/loader.js:730:27)
formio_1  |     at Module.require (internal/modules/cjs/loader.js:957:19)
formio_1  |     at require (internal/modules/cjs/helpers.js:88:18)
formio_1  |     at Object.<anonymous> (/app/src/util/util.js:4:1)
formio_1  |     at Module._compile (internal/modules/cjs/loader.js:1068:30)
formio_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
formio_1  |     at Module.load (internal/modules/cjs/loader.js:933:32)
formio_1  |     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
formio_1  |     at Module.require (internal/modules/cjs/loader.js:957:19) {
formio_1  |   code: 'MODULE_NOT_FOUND',
formio_1  |   requireStack: [ '/app/src/util/util.js', '/app/main.js' ]
formio_1  | }
formio_1 exited with code 1
```

I also tried this.  

```
docker-compose down -v --rmi all
git checkout tags/v2.2.2
docker compose up
```

Still errors, but with a different module missing:

```
formio_1  | Error: Cannot find module 'mongoose'
formio_1  | Require stack:
formio_1  | - /app/src/util/util.js
formio_1  | - /app/main.js
formio_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
formio_1  |     at Function.Module._load (internal/modules/cjs/loader.js:730:27)
```

**Comment by andrewliles** [comment]
Epic fail.  I did not first run
`npm install`
