### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by rickywu** [formio/formio#1374]
- Hosting type
  - [x] Local deployment
    - Version: 2.3.1
- Formio.js version: 2.3.1
- Frontend framework:
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. build with docker
2. docker-compose up -d
3. docker logs formio

## Observed behavior
Error: Cannot find module '@azure/ms-rest-nodeauth'
Require stack:
- /app/src/util/util.js
- /app/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/app/src/util/util.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/src/util/util.js', '/app/main.js' ]
}
internal/modules/cjs/loader.js:888
  throw err;
  ^

**Comment by DomiStyle** [comment]
Same issue here, I was able to solve it by running `npm install` on the host prior to building the application.
This is not ideal and definitely should be done while building the Docker container.

**Comment by rickywu** [comment]
Yes, I just found the reason, but it's better run npm install in Dockerfile

**Comment by link89** [comment]
Run `npm install` before `docker-compose up` doesn't solve the problem in my case.

**Comment by daneformio** [comment]
@link89 Did you try the solution outlined in https://github.com/formio/formio/issues/1503 ?

**Comment by link89** [comment]
No, I choose formily instead.

**Comment by daneformio** [comment]
I'm closing this as resolved. If someone in this thread is still having an issue with this, please reopen. Thank you.
