### ISSUE TITLE
[BUG] Date deprecation warning error in FormIO when using REACT

### ISSUE THREAD

**Issue by arogl** [formio/formio#1468]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io and [next](https://next.form.io/#/)
  - [x] Local deployment
    - Version: 7.4.0
- Formio.js version: 4.14.0-rc.12 (next)
- Frontend framework: v8.0.0-alpha.19 (next)
- Browser: Chrome
- Browser version: 104

## Steps to Reproduce
1. Create react form 
2. Add a day field, place restrictions on year, and make day first
3. Error appears in browser console and server log upon validation logic starting

## Expected behavior

No errors in browser console or hosted server logs

## Observed behavior
Log from hosted version. 
```
This form is creating an error
https://api.forms.platforms.qld.gov.au/#/project/62f43cfa68e5904456c50ac8/form/62f43e8968e5904456c52e2f/edit
 
2022-08-31T07:24:42.628407027Z Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
2022-08-31T07:24:42.628460127Z Arguments: 
2022-08-31T07:24:42.628465427Z [0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 01/01/2022, _f: undefined, _strict: undefined, _locale: [object Object]
2022-08-31T07:24:42.628469027Z Error
2022-08-31T07:24:42.628472227Z     at Function.createFromInputFallback (/src/node_modules/moment/moment.js:324:25)
2022-08-31T07:24:42.628475727Z     at configFromString (/src/node_modules/moment/moment.js:2550:19)
2022-08-31T07:24:42.628479427Z     at configFromInput (/src/node_modules/moment/moment.js:2993:13)
2022-08-31T07:24:42.628482627Z     at prepareConfig (/src/node_modules/moment/moment.js:2976:13)
2022-08-31T07:24:42.628485727Z     at createFromConfig (/src/node_modules/moment/moment.js:2943:44)
2022-08-31T07:24:42.628488827Z     at createLocalOrUTC (/src/node_modules/moment/moment.js:3037:16)
2022-08-31T07:24:42.628491927Z     at createLocal (/src/node_modules/moment/moment.js:3041:16)
2022-08-31T07:24:42.628495527Z     at hooks (/src/node_modules/moment/moment.js:16:29)
2022-08-31T07:24:42.628498727Z     at getDateSetting (/src/node_modules/formiojs/utils/utils.js:767:110)
2022-08-31T07:24:42.628501827Z     at ValidationChecker.check (/src/node_modules/formiojs/validator/Validator.js:842:51)
2022-08-31T07:24:42.628504927Z     at ValidationChecker.checkValidator (/src/node_modules/formiojs/validator/Validator.js:1001:43)
2022-08-31T07:24:42.628508027Z     at ValidationChecker.validate (/src/node_modules/formiojs/validator/Validator.js:1034:34)
2022-08-31T07:24:42.628511227Z     at /src/node_modules/formiojs/validator/Validator.js:1196:25
2022-08-31T07:24:42.628522327Z     at arrayMap (/src/node_modules/lodash/lodash.js:653:23)
2022-08-31T07:24:42.628526427Z     at Function.map (/src/node_modules/lodash/lodash.js:9622:14)
2022-08-31T07:24:42.628529427Z     at /src/node_modules/formiojs/validator/Validator.js:1195:32
2022-08-31T07:24:42.665946677Z 2022-08-31T07:24:42.665Z resourcejs:post Skipping Resource
```

Browser console log from Form.IO:

I had entered
Day: 1
Month: 1
Year: 20

```
scripts.js:39 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 31/12/2030, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://portal.form.io/scripts.js:39:8061)
    at https://portal.form.io/scripts.js:39:28312
    at https://portal.form.io/scripts.js:39:28363
    at xt (https://portal.form.io/scripts.js:39:28675)
    at Ct (https://portal.form.io/scripts.js:39:28936)
    at St (https://portal.form.io/scripts.js:39:29018)
    at i (https://portal.form.io/scripts.js:39:4983)
    at t.getDateSetting (https://portal.form.io/scripts.js:9:81393)
    at t.check (https://portal.form.io/scripts.js:120:97320)
    at t.value (https://portal.form.io/scripts.js:120:99523)
```

For code or form JSON, please enclose in a code block:

```json
{"_id":"6316bd81ce68465c9ae3af61","type":"form","tags":[],"owner":"6316bdf40cacd2abcca00be6","components":[{"label":"Day","hideInputLabels":false,"inputsLabelPosition":"top","useLocaleSettings":false,"tableView":false,"fields":{"day":{"hide":false,"required":true},"month":{"type":"number","hide":false},"year":{"minYear":1900,"maxYear":2030,"hide":false}},"dayFirst":true,"maxDate":"2030-12-31","minDate":"1900-01-01","key":"day","type":"day","input":true,"maxYear":2030,"minYear":1900,"defaultValue":"00/00/0000"}],"revisions":"","_vid":1,"title":"Test Day","name":"testDay","path":"user/register","access":[{"roles":["6316bd81ce6846540be3af46"],"type":"read_all"}],"submissionAccess":[{"roles":["6316bd81ce6846540be3af46"],"type":"create_own"}],"machineName":"zctnxbbxnrthchj:userRegister","project":"6316bd81ce68460398e3af35","created":"2022-09-06T03:24:49.431Z","modified":"2022-09-06T03:36:29.552Z","display":"form","settings":{}}
```

Previous reference found here #1063, but no resolution

using stand-alone mode does not throw the error on PaaS Form.IO

**Comment by travist** [comment]
Thanks for letting us know about this issue. We will take a look and see what we can do about getting a fix in place.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
