### ISSUE TITLE
Error in connecting to mongo db

### ISSUE THREAD

**Issue by priya30m** [formio/formio#1637]
When starting the npm server, is fails with below error. My mongod service is running and i am able to connect to mongo DB from mongodb compass.

ERROR:

Welcome to the Form.io application server!

  - Help: https://help.form.io
  - Code: https://github.com/formio
  - Love: https://form.io

D:\formio\formio-master\src\db\index.js:215
          throw new Error(`Could not connect to the given Database for server updates: ${dbUrl}.`);
                ^

Error: Could not connect to the given Database for server updates: mongodb://localhost:27017/formioapp.
    at D:\formio\formio-master\src\db\index.js:215:17
    at unlock (D:\formio\formio-master\src\db\index.js:76:14)
    at D:\formio\formio-master\src\db\index.js:214:9
    at D:\formio\formio-master\node_modules\mongodb\lib\utils.js:348:66

Node.js v18.18.0

**Comment by priya30m** [comment]
resolved after using 127.0.0.1 instead of localhost in config\default.json for mongo db url
