### ISSUE TITLE
Uncaught Error: QWeb2: Template 'formio.builder' not found

### ISSUE THREAD

**Issue by FlyingPigSolutions** [formio/formio#1672]
Uncaught Error: QWeb2: Template 'formio.builder' not found

https://SERVER.IP.ADDRESS/web/content/82955784-94d97b7/web.assets_common.js:3689
Retraçage :
Error: QWeb2: Template 'formio.builder' not found
    at Object.exception (https://SERVER.IP.ADDRESS/web/content/82955784-94d97b7/web.assets_common.js:3689:7)
    at Engine._render (https://SERVER.IP.ADDRESS/web/content/82955784-94d97b7/web.assets_common.js:3734:103)
    at Engine.render (https://SERVER.IP.ADDRESS/web/content/82955784-94d97b7/web.assets_common.js:3730:151)
    at Class._renderView (https://SERVER.IP.ADDRESS/web/content/83076034-d9453e2/web.assets_backend.js:4266:357)
    at Class._render (https://SERVER.IP.ADDRESS/web/content/83076034-d9453e2/web.assets_backend.js:1351:178)
    at Class.start (https://SERVER.IP.ADDRESS/web/content/83076034-d9453e2/web.assets_backend.js:1095:335)
    at prototype.<computed> [as start] (https://SERVER.IP.ADDRESS/web/content/82955784-94d97b7/web.assets_common.js:3816:488)
    at https://SERVER.IP.ADDRESS/web/content/82955784-94d97b7/web.assets_common.js:3949:963
    at https://SERVER.IP.ADDRESS/web/content/82955784-94d97b7/web.assets_common.js:802:681
    at fire (https://SERVER.IP.ADDRESS/web/content/82955784-94d97b7/web.assets_common.js:796:299)

Module FORM installed on UBUNTU server 16, for ODOO 11 Community
Instalation works fine

How do we got the error ?

Going to FORMS > FORM BUILDER > DEMO1 that is already existing > Clicking on FORM BUILDER button on the top hand right corner

Anywone knows why ? and how to solve it?

**Comment by brendanbond** [comment]
I'm not sure we'll be able to help very much here without a minimally reproducible example, it sounds like you're running Form.io within an Odoo installation? We'll need more information from you to be able to dive into this.

**Comment by olgabann** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you'd like to reopen the issue, please reply and we can resume the triage process.
