### ISSUE TITLE
Formio startup error：UnhandledPromiseRejectionWarning: Error: Cannot find module 'node:domain'

### ISSUE THREAD

**Issue by AldirchEugene** [formio/formio#1683]
18:51:25]Welcome to the Form.io application server!
[18:51:25]
[18:51:25]  - Help: https://help.form.io/
[18:51:25]  - Code: https://github.com/formio
[18:51:25]  - Love: https://form.io/
[18:51:25]
[18:51:25]Checking for db setup.
[18:51:25] > Setup complete.
[18:51:25]
[18:51:25]Checking for db schema updates.
[18:51:25] > No updates found.
[18:51:25]
[18:51:25]Initializing API Server.
[18:51:25](node:17) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
[18:51:25](Use `node --trace-deprecation ...` to show where the warning was created)
[18:51:25] > Mongo connection established.
[18:51:25](node:17) UnhandledPromiseRejectionWarning: Error: Cannot find module 'node:domain'
[18:51:25]Require stack:
[18:51:25]- /.npm-packages/node_modules/formio-workers/Formio.js
[18:51:25]- /.npm-packages/node_modules/formio-workers/Worker.js
[18:51:25]- /.npm-packages/node_modules/formio-workers/Thread.js
[18:51:25]- /app/src/worker/Worker.js
[18:51:25]- /app/src/util/email.js
[18:51:25]- /app/src/actions/EmailAction.js
[18:51:25]- /app/src/actions/actions.js
[18:51:25]- /app/index.js
[18:51:25]- /app/server.js
[18:51:25]- /app/main.js
[18:51:25]    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
[18:51:25]    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
[18:51:25]    at Module.require (internal/modules/cjs/loader.js:957:19)
[18:51:25]    at require (internal/modules/cjs/helpers.js:88:18)
[18:51:25]    at Object.<anonymous> (/.npm-packages/node_modules/formio-workers/Formio.js:6:16)
[18:51:25]    at Module._compile (internal/modules/cjs/loader.js:1068:30)
[18:51:25]    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
[18:51:25]    at Module.load (internal/modules/cjs/loader.js:933:32)
[18:51:25]    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
[18:51:25]    at Module.require (internal/modules/cjs/loader.js:957:19)
[18:51:25]    at require (internal/modules/cjs/helpers.js:88:18)
[18:51:25]    at Object.<anonymous> (/.npm-packages/node_modules/formio-workers/Worker.js:4:1)
[18:51:25]    at Module._compile (internal/modules/cjs/loader.js:1068:30)
[18:51:25]    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
[18:51:25]    at Module.load (internal/modules/cjs/loader.js:933:32)
[18:51:25]    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
[18:51:25](node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[18:51:25](node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by brendanbond** [comment]
We'll need more info, what version of node are you running?

**Comment by b3333l** [comment]
Same problem! Solved by updating the base image in the dockerfile from lts-alpine3.10 to 16.20.2-alpine3.18, and small fixes versions of make and gcc. lts-alpine3.10 must contain node 16.13.0 (https://hub.docker.com/layers/library/node/lts-alpine3.11/images/sha256-6338412b1f757c9bb4028e4e6513568f8bdcd16127dab3cb207c34aa1c455000), but doesn't (was discovered 14)
Fixed head of Dockerfile below:
`
FROM node:16.20.2-alpine3.18
WORKDIR /app

RUN apk update && \
    apk upgrade && \
    apk add --no-cache make && \
    apk add --no-cache g++`

**Comment by brendanbond** [comment]
Hi @b3333l @AldirchEugene I've updated the Dockerfile further in #1703 please give this a shot and let me know if you continue to run into issues.

**Comment by daneformio** [comment]
Closing this issue as solved per the linked PR. If this is still an issue, please reopen.
