### ISSUE TITLE
When trying to docker-compose up I get Unknown plugin option jsonLogic

### ISSUE THREAD

**Issue by kkrumlian** [formio/formio#1699]
Seeing this error when trying to `docker compose up`

```
formio-1  | Unknown plugin option jsonLogic
formio-1  | node:internal/modules/cjs/loader:1473
formio-1  |   return process.dlopen(module, path.toNamespacedPath(filename));
formio-1  |                  ^
formio-1  |
formio-1  | Error: Error loading shared library /app/node_modules/isolated-vm/out/isolated_vm.node: Exec format error
formio-1  |     at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
formio-1  |     at Module.load (node:internal/modules/cjs/loader:1207:32)
formio-1  |     at Module._load (node:internal/modules/cjs/loader:1023:12)
formio-1  |     at Module.require (node:internal/modules/cjs/loader:1235:19)
formio-1  |     at require (node:internal/modules/helpers:176:18)
formio-1  |     at Object.<anonymous> (/app/node_modules/isolated-vm/isolated-vm.js:1:18)
formio-1  |     at Module._compile (node:internal/modules/cjs/loader:1376:14)
formio-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
formio-1  |     at Module.load (node:internal/modules/cjs/loader:1207:32)
formio-1  |     at Module._load (node:internal/modules/cjs/loader:1023:12) {
formio-1  |   code: 'ERR_DLOPEN_FAILED'
formio-1  | }
formio-1  |
formio-1  | Node.js v20.11.0
formio-1 exited with code 1
```

Also had to update the DockerFile with adding the python3 package dependency

```
RUN apk update && \
    apk upgrade && \
    apk add make && \
    apk add python3 && \
    apk add g++
```

**Comment by brendanbond** [comment]
Hey @kkrumlian the new dependency `isolated-vm` requires you to rebuild your dependencies. Try regenerating your package-lock.json file by removing node_modules and package-lock.json and running `npm install`

**Comment by brendanbond** [comment]
Yeah, I can reproduce this. I'll try to tackle this later today

**Comment by mogul** [comment]
Reproducing in a WSL2 Ubuntu distro too, though with a different shared library mentioned.
```
formio-1  | 
formio-1  | Unknown plugin option jsonLogic
formio-1  | node:internal/modules/cjs/loader:1473
formio-1  |   return process.dlopen(module, path.toNamespacedPath(filename));
formio-1  |                  ^
formio-1  | 
formio-1  | Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/node_modules/isolated-vm/out/isolated_vm.node)
formio-1  |     at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
formio-1  |     at Module.load (node:internal/modules/cjs/loader:1207:32)
formio-1  |     at Module._load (node:internal/modules/cjs/loader:1023:12)
formio-1  |     at Module.require (node:internal/modules/cjs/loader:1235:19)
formio-1  |     at require (node:internal/modules/helpers:176:18)
formio-1  |     at Object.<anonymous> (/app/node_modules/isolated-vm/isolated-vm.js:1:18)
formio-1  |     at Module._compile (node:internal/modules/cjs/loader:1376:14)
formio-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
formio-1  |     at Module.load (node:internal/modules/cjs/loader:1207:32)
formio-1  |     at Module._load (node:internal/modules/cjs/loader:1023:12) {
formio-1  |   code: 'ERR_DLOPEN_FAILED'
formio-1  | }
formio-1  | 
formio-1  | Node.js v20.11.0
formio-1 exited with code 1
```

**Comment by erikpb** [comment]
Having the same issues. Host is OSX with Node 20.11.1 and npm 10.2.4.

**Comment by mogul** [comment]
@brendanbond any word? (I put aside what I was investigating doing with formio until this was resolved.)

**Comment by brendanbond** [comment]
@mogul @kkrumlian #1703 should fix this issue around dependency errors, can you pull down this branch and give it a shot? It's a holiday in the US today but assuming your tests go well I will try and get this reviewed and merged this week. Please note you'll still see the jsonLogic error, which is unrelated.

**Comment by mogul** [comment]
Sorry to be late responding. I can confirm this resolved the problem, thanks! 👍
