### ISSUE TITLE
Docker image fails to build

### ISSUE THREAD

**Issue by nhathaway** [formio/formio#1832]
**Describe the bug**
The docker build process falls over with an error

**Version/Branch**
formio-4.2.8
Docker version 27.3.1, build ce12230

**To Reproduce**
docker compose up -d

**Expected behavior**
It should build and run

**Screenshots**
See below for build log

**Additional context**
```
 => ERROR [formio 10/11] RUN yarn install                                                                                                  100.7s
------
 > [formio 10/11] RUN yarn install:
4.461 yarn install v1.22.22
4.672 info No lockfile found.
4.710 [1/5] Validating package.json...
4.738 [2/5] Resolving packages...
19.53 warning q@1.5.1: You or someone you depend on is using Q, the JavaScript Promise library that gave JavaScript developers strong feelings about promises. They can almost certainly migrate to the native JavaScript promise now. Thank you literally everyone for joining me in this bet against the odds. Be excellent to each other.
19.53
19.53 (For a CapTP with native promises, see @endo/eventual-send and @endo/captp)
22.09 warning eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
22.53 warning eslint > @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
22.84 warning eslint > @humanwhocodes/config-array > @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
22.90 warning eslint > file-entry-cache > flat-cache > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
22.97 warning eslint > file-entry-cache > flat-cache > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
23.02 warning eslint > file-entry-cache > flat-cache > rimraf > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
23.15 warning mocha > glob@8.1.0: Glob versions prior to v9 are no longer supported
23.16 warning mocha > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
24.91 warning supertest > superagent@8.1.2: Please upgrade to v9.0.0+ as we have fixed a public vulnerability with formidable dependency. Note that v9.0.0+ requires Node.js v14.18.0+. See https://github.com/ladjs/superagent/pull/1800 for insight. This project is supported and maintained by the team at Forward Email @ https://forwardemail.net
25.73 [3/5] Fetching packages...
61.80 [4/5] Linking dependencies...
61.81 warning "mongodb > @aws-sdk/credential-providers > @aws-sdk/credential-provider-sso > @aws-sdk/token-providers@3.692.0" has unmet peer dependency "@aws-sdk/client-sso-oidc@^3.692.0".
61.81 warning " > superagent-retry@0.6.0" has unmet peer dependency "superagent@*".
78.70 [5/5] Building fresh packages...
98.84 error /app/node_modules/isolated-vm: Command failed.
98.84 Exit code: 1
98.84 Command: prebuild-install || (node-gyp rebuild --release -j max && node-gyp clean)
98.84 Arguments:
98.84 Directory: /app/node_modules/isolated-vm
98.84 Output:
98.84 prebuild-install warn install No prebuilt binaries found (target=22.11.0 runtime=node arch=arm64 libc=musl platform=linux)
98.84 gyp info it worked if it ends with ok
98.84 gyp info using node-gyp@10.2.0
98.84 gyp info using node@22.11.0 | linux | arm64
98.84 gyp info find Python using Python version 3.11.10 found at "/usr/bin/python3"
98.84
98.84 gyp http GET https://nodejs.org/download/release/v22.11.0/node-v22.11.0-headers.tar.gz
98.84 gyp http 200 https://nodejs.org/download/release/v22.11.0/node-v22.11.0-headers.tar.gz
98.84 gyp http GET https://nodejs.org/download/release/v22.11.0/SHASUMS256.txt
98.84 gyp http 200 https://nodejs.org/download/release/v22.11.0/SHASUMS256.txt
98.84 gyp info spawn /usr/bin/python3
98.84 gyp info spawn args [
98.84 gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
98.84 gyp info spawn args 'binding.gyp',
98.84 gyp info spawn args '-f',
98.84 gyp info spawn args 'make',
98.84 gyp info spawn args '-I',
98.84 gyp info spawn args '/app/node_modules/isolated-vm/build/config.gypi',
98.84 gyp info spawn args '-I',
98.84 gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
98.84 gyp info spawn args '-I',
98.84 gyp info spawn args '/root/.cache/node-gyp/22.11.0/include/node/common.gypi',
98.84 gyp info spawn args '-Dlibrary=shared_library',
98.84 gyp info spawn args '-Dvisibility=default',
98.84 gyp info spawn args '-Dnode_root_dir=/root/.cache/node-gyp/22.11.0',
98.84 gyp info spawn args '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
98.84 gyp info spawn args '-Dnode_lib_file=/root/.cache/node-gyp/22.11.0/<(target_arch)/node.lib',
98.84 gyp info spawn args '-Dmodule_root_dir=/app/node_modules/isolated-vm',
98.84 gyp info spawn args '-Dnode_engine=v8',
98.84 gyp info spawn args '--depth=.',
98.84 gyp info spawn args '--no-parallel',
98.84 gyp info spawn args '--generator-output',
98.84 gyp info spawn args 'build',
98.84 gyp info spawn args '-Goutput_dir=.'
98.84 gyp info spawn args ]
98.84 gyp info spawn make
98.84 gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 4 ]
98.84 make: Entering directory '/app/node_modules/isolated-vm/build'
98.84   CXX(target) Release/obj.target/nortti/src/external_copy/serializer_nortti.o
98.84   CXX(target) Release/obj.target/nortti/src/isolate/allocator_nortti.o
98.84 In file included from ../src/isolate/generic/array.h:2,
98.84                  from ../src/external_copy/external_copy.h:9,
98.84                  from ../src/external_copy/serializer.h:2,
98.84                  from ../src/external_copy/serializer_nortti.cc:1:
98.84 ../src/isolate/generic/error.h:84:85: error: conversion from 'v8::Local<v8::Value> (*)(v8::Local<v8::String>, v8::Local<v8::Value>)' to 'v8::Local<v8::Value> (*)(v8::Local<v8::String>)' in a converted constant expression
98.84    84 | using RuntimeGenericError = detail::RuntimeErrorWithConstructor<v8::Exception::Error>;
98.84       |                                                                                     ^
98.84 ../src/isolate/generic/error.h:84:85: error: could not convert 'v8::Exception::Error' from 'v8::Local<v8::Value>(v8::Local<v8::String>, v8::Local<v8::Value>)' to 'v8::Local<v8::Value> (*)(v8::Local<v8::String>)'
98.84    84 | using RuntimeGenericError = detail::RuntimeErrorWithConstructor<v8::Exception::Error>;
98.84       |                                                                                     ^
98.84       |                                                                                     |
98.84       |                                                                                     v8::Local<v8::Value>(v8::Local<v8::String>, v8::Local<v8::Value>)
98.84 ../src/isolate/generic/error.h:85:86: error: conversion from 'v8::Local<v8::Value> (*)(v8::Local<v8::String>, v8::Local<v8::Value>)' to 'v8::Local<v8::Value> (*)(v8::Local<v8::String>)' in a converted constant expression
98.84    85 | using RuntimeTypeError = detail::RuntimeErrorWithConstructor<v8::Exception::TypeError>;
98.84       |                                                                                      ^
98.84 ../src/isolate/generic/error.h:85:86: error: could not convert 'v8::Exception::TypeError' from 'v8::Local<v8::Value>(v8::Local<v8::String>, v8::Local<v8::Value>)' to 'v8::Local<v8::Value> (*)(v8::Local<v8::String>)'
98.84    85 | using RuntimeTypeError = detail::RuntimeErrorWithConstructor<v8::Exception::TypeError>;
98.84       |                                                                                      ^
98.84       |                                                                                      |
98.84       |                                                                                      v8::Local<v8::Value>(v8::Local<v8::String>, v8::Local<v8::Value>)
98.84 ../src/isolate/generic/error.h:86:88: error: conversion from 'v8::Local<v8::Value> (*)(v8::Local<v8::String>, v8::Local<v8::Value>)' to 'v8::Local<v8::Value> (*)(v8::Local<v8::String>)' in a converted constant expression
98.84    86 | using RuntimeRangeError = detail::RuntimeErrorWithConstructor<v8::Exception::RangeError>;
98.84       |                                                                                        ^
98.84 ../src/isolate/generic/error.h:86:88: error: could not convert 'v8::Exception::RangeError' from 'v8::Local<v8::Value>(v8::Local<v8::String>, v8::Local<v8::Value>)' to 'v8::Local<v8::Value> (*)(v8::Local<v8::String>)'
98.84    86 | using RuntimeRangeError = detail::RuntimeErrorWithConstructor<v8::Exception::RangeError>;
98.84       |                                                                                        ^
98.84       |                                                                                        |
98.84       |                                                                                        v8::Local<v8::Value>(v8::Local<v8::String>, v8::Local<v8::Value>)
98.84 In file included from ../src/isolate/strings.h:2,
98.84                  from ../src/isolate/environment.h:13,
98.84                  from ../src/isolate/allocator_nortti.cc:2:
98.84 ../src/isolate/generic/error.h:84:85: error: conversion from 'v8::Local<v8::Value> (*)(v8::Local<v8::String>, v8::Local<v8::Value>)' to 'v8::Local<v8::Value> (*)(v8::Local<v8::String>)' in a converted constant expression
98.84    84 | using RuntimeGenericError = detail::RuntimeErrorWithConstructor<v8::Exception::Error>;
98.84       |                                                                                     ^
98.84 ../src/isolate/generic/error.h:84:85: error: could not convert 'v8::Exception::Error' from 'v8::Local<v8::Value>(v8::Local<v8::String>, v8::Local<v8::Value>)' to 'v8::Local<v8::Value> (*)(v8::Local<v8::String>)'
98.84    84 | using RuntimeGenericError = detail::RuntimeErrorWithConstructor<v8::Exception::Error>;
98.84       |                                                                                     ^
98.84       |                                                                                     |
98.84       |                                                                                     v8::Local<v8::Value>(v8::Local<v8::String>, v8::Local<v8::Value>)
98.84 ../src/isolate/generic/error.h:85:86: error: conversion from 'v8::Local<v8::Value> (*)(v8::Local<v8::String>, v8::Local<v8::Value>)' to 'v8::Local<v8::Value> (*)(v8::Local<v8::String>)' in a converted constant expression
98.84    85 | using RuntimeTypeError = detail::RuntimeErrorWithConstructor<v8::Exception::TypeError>;
98.84       |                                                                                      ^
98.84 ../src/isolate/generic/error.h:85:86: error: could not convert 'v8::Exception::TypeError' from 'v8::Local<v8::Value>(v8::Local<v8::String>, v8::Local<v8::Value>)' to 'v8::Local<v8::Value> (*)(v8::Local<v8::String>)'
98.84    85 | using RuntimeTypeError = detail::RuntimeErrorWithConstructor<v8::Exception::TypeError>;
98.84       |                                                                                      ^
98.84       |                                                                                      |
98.84       |                                                                                      v8::Local<v8::Value>(v8::Local<v8::String>, v8::Local<v8::Value>)
98.84 ../src/isolate/generic/error.h:86:88: error: conversion from 'v8::Local<v8::Value> (*)(v8::Local<v8::String>, v8::Local<v8::Value>)' to 'v8::Local<v8::Value> (*)(v8::Local<v8::String>)' in a converted constant expression
98.84    86 | using RuntimeRangeError = detail::RuntimeErrorWithConstructor<v8::Exception::RangeError>;
98.84       |                                                                                        ^
98.84 ../src/isolate/generic/error.h:86:88: error: could not convert 'v8::Exception::RangeError' from 'v8::Local<v8::Value>(v8::Local<v8::String>, v8::Local<v8::Value>)' to 'v8::Local<v8::Value> (*)(v8::Local<v8::String>)'
98.84    86 | using RuntimeRangeError = detail::RuntimeErrorWithConstructor<v8::Exception::RangeError>;
98.84       |                                                                                        ^
98.84       |                                                                                        |
98.84       |                                                                                        v8::Local<v8::Value>(v8::Local<v8::String>, v8::Local<v8::Value>)
98.84 ../src/external_copy/serializer.h: In member function 'auto ivm::BaseSerializer::Deserialize(Fn)':
98.84 ../src/external_copy/serializer.h:101:47: error: there are no arguments to 'RuntimeRangeError' that depend on a template parameter, so a declaration of 'RuntimeRangeError' must be available [-fpermissive]
98.84   101 |                                         throw RuntimeRangeError("Array buffer allocation failed");
98.84       |                                               ^~~~~~~~~~~~~~~~~
98.84 ../src/external_copy/serializer.h:101:47: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
98.84 In file included from ../src/external_copy/serializer_nortti.cc:2:
98.84 ../src/isolate/functor_runners.h: In function 'void ivm::FunctorRunners::RunCatchExternal(v8::Local<v8::Context>, F1, F2)':
98.84 ../src/isolate/functor_runners.h:42:32: error: ISO C++ forbids declaration of 'RuntimeTypeError' with no type [-fpermissive]
98.84    42 |                 } catch (const RuntimeTypeError& cc_error) {
98.84       |                                ^~~~~~~~~~~~~~~~
98.84 ../src/isolate/functor_runners.h:42:48: error: expected ')' before '&' token
98.84    42 |                 } catch (const RuntimeTypeError& cc_error) {
98.84       |                         ~                      ^
98.84       |                                                )
98.84 ../src/isolate/functor_runners.h:42:48: error: expected '{' before '&' token
98.84 ../src/isolate/functor_runners.h:42:50: error: 'cc_error' was not declared in this scope
98.84    42 |                 } catch (const RuntimeTypeError& cc_error) {
98.84       |                                                  ^~~~~~~~
98.84 ../src/isolate/functor_runners.h:45:19: error: expected primary-expression before 'catch'
98.84    45 |                 } catch (const RuntimeRangeError& cc_error) {
98.84       |                   ^~~~~
98.84 ../src/isolate/functor_runners.h:47:19: error: expected primary-expression before 'catch'
98.84    47 |                 } catch (const RuntimeGenericError& cc_error) {
98.84       |                   ^~~~~
98.84 ../src/isolate/functor_runners.h:49:19: error: expected primary-expression before 'catch'
98.84    49 |                 } catch (const detail::RuntimeErrorWithMessage& cc_error) {
98.84       |                   ^~~~~
98.84 ../src/isolate/functor_runners.h:51:19: error: expected primary-expression before 'catch'
98.84    51 |                 } catch (const RuntimeError& cc_error) {
98.84       |                   ^~~~~
98.84 In file included from ../src/isolate/generic/callbacks.h:4,
98.84                  from ../src/isolate/class_handle.h:6,
98.84                  from ../src/module/transferable.h:2,
98.84                  from ../src/external_copy/serializer_nortti.cc:3:
98.84 ../src/isolate/generic/extract_params.h: In member function 'void ivm::detail::ParamExtractor<Offset, Args>::CheckLength(std::tuple<_Args1 ...>*)':
98.84 ../src/isolate/generic/extract_params.h:97:39: error: 'RuntimeTypeError' was not declared in this scope; did you mean 'RuntimeError'?
98.84    97 |                                 throw RuntimeTypeError{CalleeName()+ " requires at least "+ std::to_string(adjusted)+ (adjusted == 1 ? " parameter" : " parameters")};
98.84       |                                       ^~~~~~~~~~~~~~~~
98.84       |                                       RuntimeError
98.84 ../src/isolate/generic/extract_params.h: In member function 'void ivm::detail::ParamExtractor<Offset, Args>::Caught(const ivm::ParamIncorrect&)':
98.84 ../src/isolate/generic/extract_params.h:111:39: error: 'RuntimeTypeError' was not declared in this scope; did you mean 'RuntimeError'?
98.84   111 |                                 throw RuntimeTypeError{CalleeName()+ " requires `this` to be "+ ex.type};
98.84       |                                       ^~~~~~~~~~~~~~~~
98.84       |                                       RuntimeError
98.84 ../src/isolate/generic/extract_params.h:113:39: error: 'RuntimeTypeError' was not declared in this scope; did you mean 'RuntimeError'?
98.84   113 |                                 throw RuntimeTypeError{CalleeName()+ " requires parameter "+ std::to_string(ii + 1)+ " to be "+ ex.type};
98.84       |                                       ^~~~~~~~~~~~~~~~
98.84       |                                       RuntimeError
98.84 In file included from ../src/isolate/class_handle.h:9:
98.84 ../src/isolate/generic/read_option.h: In function 'auto ivm::detail::ReadOptionImpl(v8::MaybeLocal<v8::Object>, Property&&, Default)':
98.84 ../src/isolate/generic/read_option.h:26:23: error: 'RuntimeTypeError' was not declared in this scope; did you mean 'RuntimeError'?
98.84    26 |                 throw RuntimeTypeError{
98.84       |                       ^~~~~~~~~~~~~~~~
98.84       |                       RuntimeError
98.84 ../src/isolate/generic/read_option.h:30:23: error: there are no arguments to 'RuntimeTypeError' that depend on a template parameter, so a declaration of 'RuntimeTypeError' must be available [-fpermissive]
98.84    30 |                 throw RuntimeTypeError(
98.84       |                       ^~~~~~~~~~~~~~~~
98.84 ../src/isolate/class_handle.h: In member function 'void ivm::ClassHandle::TemplateDefinition::Add(const char*, ivm::detail::MemberAccessorHolder, Args ...)':
98.84 ../src/isolate/class_handle.h:94:51: error: no matching function for call to 'v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>&, void (* const&)(v8::Local<v8::String>, const v8::PropertyCallbackInfo<v8::Value>&), void (* const&)(v8::Local<v8::String>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&), v8::Local<v8::String>&, v8::AccessControl, v8::PropertyAttribute)'
98.84    94 |                                 proto->SetAccessor(name_handle, impl.getter.callback, impl.setter.callback, name_handle, v8::AccessControl::DEFAULT, v8::PropertyAttribute::None);
98.84       |                                 ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
98.84 In file included from /root/.cache/node-gyp/22.11.0/include/node/v8-function.h:15,
98.84                  from /root/.cache/node-gyp/22.11.0/include/node/v8.h:33,
98.84                  from ../src/external_copy/external_copy.h:2:
98.84 /root/.cache/node-gyp/22.11.0/include/node/v8-template.h:1055:8: note: candidate: 'void v8::ObjectTemplate::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)'
98.84  1055 |   void SetAccessor(
98.84       |        ^~~~~~~~~~~
98.84 /root/.cache/node-gyp/22.11.0/include/node/v8-template.h:1058:61: note:   no known conversion for argument 5 from 'v8::AccessControl' to 'v8::PropertyAttribute'
98.84  1058 |       Local<Value> data = Local<Value>(), PropertyAttribute attribute = None,
98.84       |                                           ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
98.84 /root/.cache/node-gyp/22.11.0/include/node/v8-template.h:1049:8: note: candidate: 'void v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::PropertyAttribute, v8::SideEffectType, v8::SideEffectType)'
98.84  1049 |   void SetAccessor(
98.84       |        ^~~~~~~~~~~
98.84 /root/.cache/node-gyp/22.11.0/include/node/v8-template.h:1052:61: note:   no known conversion for argument 5 from 'v8::AccessControl' to 'v8::PropertyAttribute'
98.84  1052 |       Local<Value> data = Local<Value>(), PropertyAttribute attribute = None,
98.84       |                                           ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
98.84 ../src/isolate/class_handle.h: In static member function 'static void ivm::ClassHandle::PrivateConstructor(const v8::FunctionCallbackInfo<v8::Value>&)':
98.84 ../src/isolate/class_handle.h:152:31: error: 'RuntimeTypeError' was not declared in this scope; did you mean 'RuntimeError'?
98.84   152 |                         throw RuntimeTypeError(detail::CalleeName(info)+ " constructor is private");
98.84       |                               ^~~~~~~~~~~~~~~~
98.84       |                               RuntimeError
98.84 ../src/isolate/class_handle.h: In lambda function:
98.84 ../src/isolate/class_handle.h:324:39: error: there are no arguments to 'RuntimeTypeError' that depend on a template parameter, so a declaration of 'RuntimeTypeError' must be available [-fpermissive]
98.84   324 |                                 throw RuntimeTypeError(detail::CalleeName(info)+ " must be called with `new`");
98.84       |                                       ^~~~~~~~~~~~~~~~
98.84 make: *** [nortti.target.mk:158: Release/obj.target/nortti/src/isolate/allocator_nortti.o] Error 1
98.84 make: *** Waiting for unfinished jobs....
98.84 make: *** [nortti.target.mk:158: Release/obj.target/nortti/src/external_copy/serializer_nortti.o] Error 1
98.84 make: Leaving directory '/app/node_modules/isolated-vm/build'
98.84 gyp ERR! build error
98.84 gyp ERR! stack Error: `make` failed with exit code: 2
98.84 gyp ERR! stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:216:23)
98.84 gyp ERR! System Linux 6.8.0-1014-raspi
98.84 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "max"
98.84 gyp ERR! cwd /app/node_modules/isolated-vm
98.84 gyp ERR! node -v v22.11.0
98.84 gyp ERR! node-gyp -v v10.2.0
98.84 gyp ERR! not ok
98.84 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn install" did not complete successfully: exit code: 1
```

**Comment by nhathaway** [comment]
Same happens on formio-4.3.0-rc.36

**Comment by EduardCM** [comment]
Modifying the Dockerfile to use node:20-alpine3.19 image instead of node:lts-alpine3.19 fixes the issue.

**Comment by bodybybuddha** [comment]
I get a different error if I change the node line as @EduardCM  had mentioned - log just repeats the following:

```
formio-1  | Node.js v20.18.0
formio-1  | node:internal/modules/cjs/loader:641
formio-1  |       throw e;
formio-1  |       ^
formio-1  |
formio-1  | Error: Cannot find module '/app/node_modules/@formio/js/lib/cjs/index.js'
formio-1  |     at createEsmNotFoundErr (node:internal/modules/cjs/loader:1262:15)
formio-1  |     at finalizeEsmResolution (node:internal/modules/cjs/loader:1250:15)
formio-1  |     at resolveExports (node:internal/modules/cjs/loader:634:14)
formio-1  |     at Module._findPath (node:internal/modules/cjs/loader:724:31)
formio-1  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1211:27)
formio-1  |     at Module._load (node:internal/modules/cjs/loader:1051:27)
formio-1  |     at Module.require (node:internal/modules/cjs/loader:1311:19)
formio-1  |     at require (node:internal/modules/helpers:179:18)
formio-1  |     at Object.<anonymous> (/app/src/util/util.js:19:16)
formio-1  |     at Module._compile (node:internal/modules/cjs/loader:1469:14) {
formio-1  |   code: 'MODULE_NOT_FOUND',
formio-1  |   path: '/app/node_modules/@formio/js/package.json'
formio-1  | }
```

**Comment by shlroland** [comment]
> node:20-alpine3.19

same error

**Comment by EduardCM** [comment]
Here is the Dockerfile I was^1 using, it builds and runs without problems.

```
# Used by docker-compose.yml to deploy the formio application
# (When modified, you must include `--build` )
# -----------------------------------------------------------

# Use Node image, maintained by Docker:
# hub.docker.com/r/_/node/
FROM node:20-alpine3.19

# "bcrypt" requires python/make/g++, all must be installed in alpine
# (note: using pinned versions to ensure immutable build environment)
RUN apk update && \
    apk upgrade && \
    apk add make && \
    apk add python3 && \
    apk add g++ && \
    apk add git

# Use https to avoid requiring ssh keys for public repos.
RUN git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

# Copy source dependencies
COPY package.json /app/
COPY default-template.json /app/
COPY yarn.lock /app/

WORKDIR /app

# install dependencies
RUN yarn global add node-gyp
# RUN yarn add prebuild-install
RUN yarn add @popperjs/core@^2.11.8 superagent
RUN yarn install

# build the client application
COPY portal/ /app/portal/
RUN yarn build
RUN apk del git

# Copy source dependencies
COPY src/ /app/src/
COPY *.js /app/
COPY *.txt /app/
COPY config/ /app/config


# Set this to inspect more from the application. Examples:
#   DEBUG=formio:db (see index.js for more)
#   DEBUG=formio:*
ENV DEBUG=""


# This will initialize the application based on
# some questions to the user (login email, password, etc.)
ENTRYPOINT [ "node", "--no-node-snapshot", "main" ]

```

^1 I ended up downgrading to an older formio version because the current one doesn't like being served from a sub directory on my server.

**Comment by brendanbond** [comment]
Yeah because we're right in front of a big release, and `master` is technically our development branch, you may hit some snags with the Docker image. It looks like LTS is now 22, so I'll make a PR to pin it to 20 until we can figure out what about 22 is causing issues with `isolated-vm`.

**Comment by brendanbond** [comment]
This should be resolved, if there are any more issues let us know, thanks
