### ISSUE TITLE
Cannot run the formio server [Error: Could not find the formio lock to unlock]

### ISSUE THREAD

**Issue by kloudsys** [formio/formio#1837]
I am installing formio in Ubuntu 20 LTS in vultr. 
I am not using docker-compose. I have tried few times. for some reason the port of docker seems not accessible from outside.]

Anyway, I am trying to install mongo and formio manually. mongo seems workings fine
 ```
 MongoDB shell version v5.0.30
  connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
  Implicit session: session { "id" : UUID("0b0a4e14-a094-4285-bd8d-42eeff7fc3e6") }
  MongoDB server version: 5.0.30
```

~/formio$ node --version
v20.18.1
~/formio$ npm --version
10.9.1

If I run server.js I do not see any output. 
      ~/formio$ DEBUG=formio:* sudo node server.js 
Then I tried to use main.js and I see following error.
       ~/formio$ DEBUG=formio:* sudo node main.js
```

/home/linuxuser/formio/src/db/index.js:95
      throw new Error('Could not find the formio lock to unlock..');
            ^

Error: Could not find the formio lock to unlock..
    at unlock (/home/linuxuser/formio/src/db/index.js:95:13)
    at Object.initialize (/home/linuxuser/formio/src/db/index.js:735:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async router.init (/home/linuxuser/formio/index.js:338:16)
Node.js v20.18.1
```
Can someone help me please.  thank you.

**Comment by kloudsys** [comment]
it was db connectivity issue
