### ISSUE TITLE
Errors after login

### ISSUE THREAD

**Issue by taoyuan** [formio/formio#205]
Fresh install, then login, then throws:

```sh
/Users/taoyuan/temp/formio/node_modules/mongoose/lib/model.js:3002
      throw new Error('If you are populating a virtual, you must set the ' +
      ^

Error: If you are populating a virtual, you must set the localField and foreignField options
    at getModelsMapForPopulate (/Users/taoyuan/temp/formio/node_modules/mongoose/lib/model.js:3002:13)
    at populate (/Users/taoyuan/temp/formio/node_modules/mongoose/lib/model.js:2647:15)
    at _populate (/Users/taoyuan/temp/formio/node_modules/mongoose/lib/model.js:2615:5)
    at Function.Model.populate (/Users/taoyuan/temp/formio/node_modules/mongoose/lib/model.js:2575:5)
    at Immediate.cb (/Users/taoyuan/temp/formio/node_modules/mongoose/lib/query.js:1103:17)
    at Immediate.<anonymous> (/Users/taoyuan/temp/formio/node_modules/mquery/lib/utils.js:137:16)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by taoyuan** [comment]
It seems like that the error throws at `mongoose@4.6.6`

**Comment by travist** [comment]
I believe this was logged @ mongoose and they have it on their radar to fix. From what I understand, they will roll out a new one that will fix it soon.

**Comment by travist** [comment]
Ok, I was able to fix this within our build to ensure we don't call the populate method on mongoose unless we must. Latest version should fix this problem.
