### ISSUE TITLE
Error in installation 

### ISSUE THREAD

**Issue by keshvari** [formio/formio#223]
I walk through the installation guide but finally I get this error . the readline.js file only contains 53 line

readline.js:73
    terminal = !!output.isTTY;
                       ^
TypeError: Cannot read property 'isTTY' of undefined
    at new Interface (readline.js:73:24)
    at Object.exports.createInterface (readline.js:39:10)
    at module.exports (/home/ali/projects/formio2/server.js:19:32)
    at Object.<anonymous> (/home/ali/projects/formio2/main.js:5:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by travist** [comment]
What OS are you using and what version of Node.js?

**Comment by keshvari** [comment]
Upgrading to latest version of node v7.2.1 fixed my issue
