### ISSUE TITLE
 Mongoose: mpromise depricated

### ISSUE THREAD

**Issue by keshvari** [formio/formio#225]
I try installing formio with node version v7.2.1 and mongo db version  v2.4.9  but when I run `node main` and I choose each one of options I get following error :

(node:13521) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
{ MongooseError: role validation failed
    at ValidationError (/home/ali/projects/formio/node_modules/mongoose/lib/error/validation.js:23:11)
    at model.Document.invalidate (/home/ali/projects/formio/node_modules/mongoose/lib/document.js:1485:32)
    at /home/ali/projects/formio/node_modules/mongoose/lib/document.js:1361:17
    at validate (/home/ali/projects/formio/node_modules/mongoose/lib/schematype.js:705:7)
    at /home/ali/projects/formio/node_modules/mongoose/lib/schematype.js:736:11
    at /home/ali/projects/formio/src/models/Role.js:53:16
    at /home/ali/projects/formio/node_modules/mongoose/lib/model.js:3408:16
    at /home/ali/projects/formio/node_modules/mongoose/node_modules/kareem/index.js:207:48
    at /home/ali/projects/formio/node_modules/mongoose/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  errors: 
   { title: 
      { MongooseError: Role title must be unique.
          at ValidatorError (/home/ali/projects/formio/node_modules/mongoose/lib/error/validator.js:24:11)
          at validate (/home/ali/projects/formio/node_modules/mongoose/lib/schematype.js:704:13)
          at /home/ali/projects/formio/node_modules/mongoose/lib/schematype.js:736:11
          at /home/ali/projects/formio/src/models/Role.js:53:16
          at /home/ali/projects/formio/node_modules/mongoose/lib/model.js:3408:16
          at /home/ali/projects/formio/node_modules/mongoose/node_modules/kareem/index.js:207:48
          at /home/ali/projects/formio/node_modules/mongoose/node_modules/kareem/index.js:127:16
          at _combinedTickCallback (internal/process/next_tick.js:67:7)
          at process._tickCallback (internal/process/next_tick.js:98:9)
        message: 'Role title must be unique.',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'user defined',
        path: 'title',
        value: 'Administrator' } },
  message: 'role validation failed',
  name: 'ValidationError' }
role validation failed

**Comment by zackurben** [comment]
Thanks for the issue report, which OS are you on?

**Comment by keshvari** [comment]
I am on ubuntu 14.04 machine.

**Comment by travist** [comment]
This should be resolved with latest version.
