### ISSUE TITLE
Export submissions

### ISSUE THREAD

**Issue by LeMamin** [formio/formio#286]
Hello,

I have this error when I want export the submissions data from BackEnd Formio app.
I am using the "service tracker" app. I have this problem with the "Customer Survey" form and not with the "Service Agreement" form.

```
D:\Wilkeo\formio\node_modules\mongodb\lib\utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:87:11)
    at urlParse (url.js:81:5)
    at Object.urlResolve [as resolve] (url.js:637:10)
    at D:\Wilkeo\formio\src\export\export.js:68:34
    at D:\Wilkeo\formio\node_modules\lodash\lodash.js:4944:15
    at baseForOwn (D:\Wilkeo\formio\node_modules\lodash\lodash.js:3001:24)
    at D:\Wilkeo\formio\node_modules\lodash\lodash.js:4913:18
    at Function.forEach (D:\Wilkeo\formio\node_modules\lodash\lodash.js:9359:14)
    at addUrl (D:\Wilkeo\formio\src\export\export.js:64:15)
    at Stream.<anonymous> (D:\Wilkeo\formio\src\export\export.js:88:15)
    at Stream.stream.write (D:\Wilkeo\formio\node_modules\through\index.js:26:11)
    at QueryCursor.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at QueryCursor.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at QueryCursor.Readable.push (_stream_readable.js:134:10)
    at D:\Wilkeo\formio\node_modules\mongoose\lib\querycursor.js:71:11
    at D:\Wilkeo\formio\node_modules\mongoose\lib\querycursor.js:310:5
    at model.Document.init (D:\Wilkeo\formio\node_modules\mongoose\lib\document.js:337:5)
    at _create (D:\Wilkeo\formio\node_modules\mongoose\lib\querycursor.js:306:12)
    at D:\Wilkeo\formio\node_modules\mongoose\lib\querycursor.js:271:17
    at handleCallback (D:\Wilkeo\formio\node_modules\mongodb\lib\utils.js:95:56)
```

OS : Windows
Node : 6.9.5
Angular : 1.6
Browser : Chrome 56.0.2924.87

I am using "service tracker" app.

Thanks,

**Comment by LeMamin** [comment]
Problem fix : 
/src/export/export.js line 68 : field.url = _url.resolve(router.formio.config.**host**, fieldUrl);

**Comment by LeMamin** [comment]
Do you want a pull request?

**Comment by zackurben** [comment]
@LeMamin sure, pull requests are always welcome! Part of the issue is in our app too, somehow our variable diverged from whats used in this lib: `host` vs `apiHost`

So I need to put a fix in for that so they are both the same.

**Comment by LeMamin** [comment]
Thanks, 

but i have not permission to push my fix branch. 

> git push origin bugfix/apiHostIssue
remote: Permission to formio/formio.git denied to LeMamin.
fatal: unable to access 'https://github.com/formio/formio.git/': The requested URL returned error: 403

**Comment by LeMamin** [comment]
@zackurben Thanks, 

but i have not permission to push my fix branch. 

> git push origin bugfix/apiHostIssue
remote: Permission to formio/formio.git denied to LeMamin.
fatal: unable to access 'https://github.com/formio/formio.git/': The requested URL returned error: 403

**Comment by GuillaumeSmaha** [comment]
@LeMamin You have to create a fork of the project.
Then, you have to add in your cloned git directory the forked repository with the command :

     cd your/git/directory
    git remote add LeMamin https://github.com/LeMamin/formio.git

Then, you can push on your repository :

    git push --set-upstream LeMamin bugfix/apiHostIssue

Finally, on https://github.com/formio/formio a pull request will be proposed by GitHub.

**Comment by zackurben** [comment]
Thanks for the help @GuillaumeSmaha 👍
