### ISSUE TITLE
npm start fail on Windows 7 (6.1.7601 Service Pack 1 Build 7601)

### ISSUE THREAD

**Issue by mark-walle** [formio/formio#373]
Thank you in advice for help or recommendations.

I've been following the instructions in this repo's main README file to install and run. Versions are all up to date, and mongod is running in another cmd window. When I execute the `npm start` command, I run into the following errors and the app won't start.

```
PS C:\formio> npm start

> formio@1.18.8 start C:\formio
> npm run version && node main.js


> formio@1.18.8 version C:\formio
> check-node-version --node '>=6.0.0'

C:\formio\node_modules\semver\semver.js:678
    throw new TypeError('Invalid comparator: ' + comp);
    ^

TypeError: Invalid comparator: '
    at Comparator.parse (C:\formio\node_modules\semver\semver.js:678:11)
    at new Comparator (C:\formio\node_modules\semver\semver.js:662:8)
    at C:\formio\node_modules\semver\semver.js:780:12
    at Array.map (native)
    at Range.parseRange (C:\formio\node_modules\semver\semver.js:779:13)
    at Range.<anonymous> (C:\formio\node_modules\semver\semver.js:721:17)
    at Array.map (native)
    at new Range (C:\formio\node_modules\semver\semver.js:720:40)
    at C:\formio\node_modules\check-node-version\index.js:119:32
    at module.exports (C:\formio\node_modules\map-values\index.js:9:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! formio@1.18.8 version: `check-node-version --node '>=6.0.0'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the formio@1.18.8 version script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MWALLE\AppData\Roaming\npm-cache\_logs\2017-06-28T15_29_10_220Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! formio@1.18.8 start: `npm run version && node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the formio@1.18.8 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MWALLE\AppData\Roaming\npm-cache\_logs\2017-06-28T15_29_10_266Z-debug.log
PS C:\formio> more < C:\Users\MWALLE\AppData\Roaming\npm-cache\_logs\2017-06-28T15_29_10_266Z-debug.log
At line:1 char:6
+ more < C:\Users\MWALLE\AppData\Roaming\npm-cache\_logs\2017-06-28T15_29_10_266Z- ...
+      ~
The '<' operator is reserved for future use.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported
```

Looking at that log:
```
PS C:\formio> type C:\Users\MWALLE\AppData\Roaming\npm-cache\_logs\2017-06-28T15_29_10_266Z-debug.log | more
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.0.4
3 info using node@v6.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle formio@1.18.8~prestart: formio@1.18.8
6 silly lifecycle formio@1.18.8~prestart: no script for prestart, continuing
7 info lifecycle formio@1.18.8~start: formio@1.18.8
8 verbose lifecycle formio@1.18.8~start: unsafe-perm in lifecycle true
9 verbose lifecycle formio@1.18.8~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\formio\node_
modules\.bin;C:\Windows\system32\WindowsPowerShell\v1.0\;C:\ProgramData\Oracle\Java\javapath;C:\Python27\;C:\Python27\Sc
ripts;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Wi
ndows\System32\Wbem;C:\Program Files (x86)\Microsoft Application Virtualization Client;C:\Windows\System32\WindowsPowerS
hell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Manage
ment Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel
\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\Wireless
Common\;C:\SWTOOLS\ReadyApps;C:\Program Files\Lenovo\Touch Fingerprint Software\;C:\Strawberry\c\bin;C:\Strawberry\perl\
site\bin;C:\Strawberry\perl\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Too
lkit\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\MWALLE\AppData\Roa
ming\npm
10 verbose lifecycle formio@1.18.8~start: CWD: C:\formio
11 silly lifecycle formio@1.18.8~start: Args: [ '/d /s /c', 'npm run version && node main.js' ]
12 silly lifecycle formio@1.18.8~start: Returned: code: 1  signal: null
13 info lifecycle formio@1.18.8~start: Failed to exec start script
14 verbose stack Error: formio@1.18.8 start: `npm run version && node main.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16
)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid formio@1.18.8
16 verbose cwd C:\formio
17 verbose Windows_NT 6.1.7601
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "s
tart"
19 verbose node v6.11.0
20 verbose npm  v5.0.4
21 error code ELIFECYCLE
22 error errno 1
23 error formio@1.18.8 start: `npm run version && node main.js`
23 error Exit status 1
24 error Failed at the formio@1.18.8 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

Double checking my versions of node and npm:
```
PS C:\formio> node --version
v6.11.0
PS C:\formio> npm --version
5.0.4
```

OS version information:
```
PS C:\formio> systeminfo | findstr /C:"OS"
OS Name:                   Microsoft Windows 7 Enterprise
OS Version:                6.1.7601 Service Pack 1 Build 7601
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
```

**Comment by indrajith-chandrashekar** [comment]
Hi Mark,

We are facing the exact issue while running npm start. However the versions of npm and node we are using are:
npm: 5.3.0
node: 6.11.1

could you share your solution which fixed the above issue please?

Thanks,
Indrajith

**Comment by mark-walle** [comment]
use command ```node main``` instead of ```npm start```
