### ISSUE TITLE
Can't Start form.io

### ISSUE THREAD

**Issue by Arifi** [formio/formio#427]
Just after i fixed this issue #426  i got this new one with the next command `npm start`

```
E:\SW\Developement\formio>npm start

> formio@1.20.0 start E:\SW\Developement\formio
> npm run version && node main.js

npm WARN invalid config loglevel="notice"

> formio@1.20.0 version E:\SW\Developement\formio
> check-node-version --node '>=6.0.0'

E:\SW\Developement\formio\node_modules\semver\semver.js:678
    throw new TypeError('Invalid comparator: ' + comp);
    ^

TypeError: Invalid comparator: '
    at Comparator.parse (E:\SW\Developement\formio\node_modules\semver\semver.js
:678:11)
    at new Comparator (E:\SW\Developement\formio\node_modules\semver\semver.js:6
62:8)
    at E:\SW\Developement\formio\node_modules\semver\semver.js:828:12
    at Array.map (native)
    at Range.parseRange (E:\SW\Developement\formio\node_modules\semver\semver.js
:827:13)
    at Range.<anonymous> (E:\SW\Developement\formio\node_modules\semver\semver.j
s:769:17)
    at Array.map (native)
    at new Range (E:\SW\Developement\formio\node_modules\semver\semver.js:768:40
)
    at E:\SW\Developement\formio\node_modules\check-node-version\index.js:119:32

    at module.exports (E:\SW\Developement\formio\node_modules\map-values\index.j
s:9:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! formio@1.20.0 version: `check-node-version --node '>=6.0.0'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the formio@1.20.0 version script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mourad\AppData\Roaming\npm-cache\_logs\2017-10-14T23_22_53
_748Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! formio@1.20.0 start: `npm run version && node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the formio@1.20.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mourad\AppData\Roaming\npm-cache\_logs\2017-10-14T23_22_53
_819Z-debug.log

E:\SW\Developement\formio>
```

Any help ?

**Comment by jdecourbe** [comment]
It seems I have the same problem with formio 1.20.2:
C:\Users\IJDE7484\Documents\Personnel\techno\formio>npm start

> formio@1.20.2 start C:\Users\IJDE7484\Documents\Personnel\techno\formio
> npm run version && node main.js


> formio@1.20.2 version C:\Users\IJDE7484\Documents\Personnel\techno\formio
> check-node-version --node '>=6.0.0'

C:\Users\IJDE7484\Documents\Personnel\techno\formio\node_modules\semver\semver.j
s:678
    throw new TypeError('Invalid comparator: ' + comp);
    ^

TypeError: Invalid comparator: '
    at Comparator.parse (C:\Users\IJDE7484\Documents\Personnel\techno\formio\nod
e_modules\semver\semver.js:678:11)
    at new Comparator (C:\Users\IJDE7484\Documents\Personnel\techno\formio\node_
modules\semver\semver.js:662:8)
    at C:\Users\IJDE7484\Documents\Personnel\techno\formio\node_modules\semver\s
emver.js:828:12
    at Array.map (native)
    at Range.parseRange (C:\Users\IJDE7484\Documents\Personnel\techno\formio\nod
e_modules\semver\semver.js:827:13)
    at Range.<anonymous> (C:\Users\IJDE7484\Documents\Personnel\techno\formio\no
de_modules\semver\semver.js:769:17)
    at Array.map (native)
    at new Range (C:\Users\IJDE7484\Documents\Personnel\techno\formio\node_modul
es\semver\semver.js:768:40)
    at C:\Users\IJDE7484\Documents\Personnel\techno\formio\node_modules\check-no
de-version\index.js:119:32
    at module.exports (C:\Users\IJDE7484\Documents\Personnel\techno\formio\node_
modules\map-values\index.js:9:18)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "version"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! formio@1.20.2 version: `check-node-version --node '>=6.0.0'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the formio@1.20.2 version script 'check-node-version --node '
>=6.0.0''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the formio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     check-node-version --node '>=6.0.0'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs formio
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls formio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\IJDE7484\Documents\Personnel\techno\formio\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! formio@1.20.2 start: `npm run version && node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the formio@1.20.2 start script 'npm run version && node main.
js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the formio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run version && node main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs formio
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls formio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\IJDE7484\Documents\Personnel\techno\formio\npm-debug.log

C:\Users\IJDE7484\Documents\Personnel\techno\formio>

**Comment by Arifi** [comment]
i've managed to start the app by changin line 12 on `packege.json` with this :
`12   "version": "check-node-version --node 6.11.4"`

It's not a fix but it worked for me

**Comment by r04drunn3r** [comment]
The problem seems to be with the single quote in the package.json.

Replace
`"check-node-version --node '>=6.0.0'"`
with
`"check-node-version --node \">=6.0.0\""`

**Comment by Arifi** [comment]
Oh... so obvious..

**Comment by todduk** [comment]
I reported this back in July as issue #380 but didn't include the text of the error so it wasn't as easily searchable as it should have been, apologies.

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
