### ISSUE TITLE
client.zip 404

### ISSUE THREAD

**Issue by cfsilence** [formio/formio#583]
When trying to install in a new Docker container, I'm getting errors while unzipping the client download.

Turns out it's actually an issue with the download itself, as the following URL returns a 404:

https://nodeload.github.com/formio/formio-app-formio/zip/master/client.zip

Has the hosted client zip moved to a new location?

**Comment by gismomtl** [comment]
issue is still accurate.. file access is working from time to time .. else "downloadClient" task is failing

**Comment by randallknutson** [comment]
We haven't changed anything recently with formio-app-formio. I wonder if github has changed something that is breaking the connection. We'll take a look into it. For now, you can download the client manually and place it in the /client directory in the project.

**Comment by jhen1422** [comment]
@gismomtl We have ran a fresh install and client was downloaded just fine for us. Can you confirm you had a strong internet connection or if you were behind a firewall?

**Comment by koenaad** [comment]
Hi @jhen1422, I would like to re-open this issue. I encounter the same issue.

I get the following errors when running`docker-compose up`:

```
formio_1  | Initializing API Server.
formio_1  |  > Mongo connection established.
formio_1  | Installing...
prompt: Are you sure you wish to install? (y/N):  
formio_1  | Which Github application would you like to install?
formio_1  |   1.) None
formio_1  |   2.) https://github.com/formio/formio-app-humanresources
formio_1  |   3.) https://github.com/formio/formio-app-servicetracker
formio_1  |   4.) https://github.com/formio/formio-app-todo
formio_1  |   5.) https://github.com/formio/formio-app-salesquote
formio_1  |   6.) https://github.com/formio/formio-app-basic
formio_1  | 
formio_1  | Or, you can provide a custom Github repository...
formio_1  | 
prompt: GitHub repository or selection?:  (1) Downloading client...
formio_1  | events.js:187
formio_1  |       throw er; // Unhandled 'error' event
formio_1  |       ^
formio_1  | 
formio_1  | Error: Client network socket disconnected before secure TLS connection was established
formio_1  |     at connResetException (internal/errors.js:570:14)
formio_1  |     at TLSSocket.onConnectEnd (_tls_wrap.js:1361:19)
formio_1  |     at Object.onceWrapper (events.js:299:28)
formio_1  |     at TLSSocket.emit (events.js:215:7)
formio_1  |     at endReadableNT (_stream_readable.js:1183:12)
formio_1  |     at processTicksAndRejections (internal/process/task_queues.js:80:21)
formio_1  | Emitted 'error' event on Request instance at:
formio_1  |     at Request.onRequestError (/app/node_modules/request/request.js:881:8)
formio_1  |     at ClientRequest.emit (events.js:210:5)
formio_1  |     at TLSSocket.socketErrorListener (_http_client.js:406:9)
formio_1  |     at TLSSocket.emit (events.js:210:5)
formio_1  |     at emitErrorNT (internal/streams/destroy.js:92:8)
formio_1  |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
formio_1  |     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
formio_1  |   code: 'ECONNRESET',
formio_1  |   path: null,
formio_1  |   host: 'nodeload.github.com',
formio_1  |   port: 443,
formio_1  |   localAddress: undefined
formio_1  | }
formio_formio_1 exited with code 1
```

The install scripts attempt to download a file from `nodeload.github.com`, but this does not seem valid.
The Github API mentions you should use `codeload.github.com`: https://developer.github.com/v3/repos/contents/#get-archive-link

**Comment by srinathganesh1** [comment]
I have a similar error on install

```
formio_1   | Which Github application would you like to install?
formio_1   |   1.) None
formio_1   |   2.) https://github.com/formio/formio-app-humanresources
formio_1   |   3.) https://github.com/formio/formio-app-servicetracker
formio_1   |   4.) https://github.com/formio/formio-app-todo
formio_1   |   5.) https://github.com/formio/formio-app-salesquote
formio_1   |   6.) https://github.com/formio/formio-app-basic
formio_1   | 
formio_1   | Or, you can provide a custom Github repository...
formio_1   | 
prompt: GitHub repository or selection?:  (1) Downloading client...
formio_1   | events.js:187
formio_1   |       throw er; // Unhandled 'error' event
formio_1   |       ^
formio_1   | 
formio_1   | Error: connect ETIMEDOUT 13.127.152.42:443
formio_1   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)
formio_1   | Emitted 'error' event on Request instance at:
formio_1   |     at Request.onRequestError (/app/node_modules/request/request.js:881:8)
formio_1   |     at ClientRequest.emit (events.js:210:5)
formio_1   |     at TLSSocket.socketErrorListener (_http_client.js:406:9)
formio_1   |     at TLSSocket.emit (events.js:210:5)
formio_1   |     at emitErrorNT (internal/streams/destroy.js:92:8)
formio_1   |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
formio_1   |     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
formio_1   |   errno: 'ETIMEDOUT',
formio_1   |   code: 'ETIMEDOUT',
formio_1   |   syscall: 'connect',
formio_1   |   address: '13.127.152.42',
formio_1   |   port: 443
formio_1   | }
formio_formio_1 exited with code 1

```
