### ISSUE TITLE
mongoose v5.0.16+ breaks connection with Mongo Cluster (cyclic dependency detected)

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio#589]
Since v1.27.5 formio cannot connect to mongodb cluser (using Mongodb Atlas).  Mongo string used that worked prior to v1.27.5 is:

```
mongodb://<user>:<password>@fomio-demo-shard-00-00-infnd.mongodb.net:27017,fomio-demo-shard-00-01-infnd.mongodb.net:27017,fomio-demo-shard-00-02-infnd.mongodb.net:27017/<dbname>?ssl=true&replicaSet=fomio-demo-shard-0&authSource=admin&retryWrites=true.
```

Tried using the following node versions with similar results:
- v6.14.2
- v8.9.4
- v8.11.1

Using node v6 start script hangs up at `Installing...`

The steps to recreate this error are:

```
git clone git:github.com:formio/formio.git /src/formio
cd /src/formio
npm install
# modify mongodb string in config/default.json
npm start
```

The error output is (in this case using v1.28.0):

```
> formio@1.28.0 start /src/formio
> npm run version && node main.js


> formio@1.28.0 version /src/formio
> check-node-version --node '>=6.0.0'


  __  __                          _       __
 / / / _| ___  _ __ _ __ ___     (_) ___  \ \
/ / | |_ / _ \| '__| '_ ` _ \    | |/ _ \  \ \
\ \ |  _| (_) | |  | | | | | | _ | | (_) | / /
 \_\|_|  \___/|_|  |_| |_| |_|(_)|_|\___/ /_/

Welcome to the Form.io application server!

  - Help: https://help.form.io
  - Code: https://github.com/formio
  - Love: https://form.io

Checking for db install.
 > No install found. Starting new install.
 > Performing install.
 > Install complete.

Checking for db schema updates.
 > No updates found.

Initializing API Server.
 > Mongo connection established.
Installing...
prompt: Are you sure you wish to install? (y/N):
/src/formio/node_modules/mongoose/lib/utils.js:429
        throw err;
        ^

Error: cyclic dependency detected
    at serializeObject (/src/formio/node_modules/bson/lib/bson/parser/serializer.js:331:34)
    at serializeInto (/src/formio/node_modules/bson/lib/bson/parser/serializer.js:934:17)
    at serializeObject (/src/formio/node_modules/bson/lib/bson/parser/serializer.js:345:18)
    at serializeInto (/src/formio/node_modules/bson/lib/bson/parser/serializer.js:934:17)
    at serializeObject (/src/formio/node_modules/bson/lib/bson/parser/serializer.js:345:18)
    at serializeInto (/src/formio/node_modules/bson/lib/bson/parser/serializer.js:934:17)
    at serializeObject (/src/formio/node_modules/bson/lib/bson/parser/serializer.js:345:18)
    at serializeInto (/src/formio/node_modules/bson/lib/bson/parser/serializer.js:934:17)
    at serializeObject (/src/formio/node_modules/bson/lib/bson/parser/serializer.js:345:18)
    at serializeInto (/src/formio/node_modules/bson/lib/bson/parser/serializer.js:934:17)
    at serializeObject (/src/formio/node_modules/bson/lib/bson/parser/serializer.js:345:18)
    at serializeInto (/src/formio/node_modules/bson/lib/bson/parser/serializer.js:934:17)
    at serializeObject (/src/formio/node_modules/bson/lib/bson/parser/serializer.js:345:18)
    at serializeInto (/src/formio/node_modules/bson/lib/bson/parser/serializer.js:934:17)
    at serializeObject (/src/formio/node_modules/bson/lib/bson/parser/serializer.js:345:18)
    at serializeInto (/src/formio/node_modules/bson/lib/bson/parser/serializer.js:934:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! formio@1.28.0 start: `npm run version && node main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the formio@1.28.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /src/.npm/_logs/2018-05-15T14_41_49_436Z-debug.log
```

NPM log

```
0 info it worked if it ends with ok
1 verbose cli [ '/src/.nvm/versions/node/v8.9.4/bin/node',
1 verbose cli   '/src/.nvm/versions/node/v8.9.4/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle formio@1.28.0~prestart: formio@1.28.0
6 info lifecycle formio@1.28.0~start: formio@1.28.0
7 verbose lifecycle formio@1.28.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle formio@1.28.0~start: PATH: /src/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/src/formio/node_modules/.bin:/src/.nvm/versions/node/v8.9.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle formio@1.28.0~start: CWD: /src/formio-v1.29.0
10 silly lifecycle formio@1.28.0~start: Args: [ '-c', 'npm run version && node main.js' ]
11 silly lifecycle formio@1.28.0~start: Returned: code: 1  signal: null
12 info lifecycle formio@1.28.0~start: Failed to exec start script
13 verbose stack Error: formio@1.28.0 start: `npm run version && node main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/src/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/src/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid formio@1.28.0
15 verbose cwd /src/formio
16 verbose Linux 4.4.0-43-Microsoft
17 verbose argv "/src/.nvm/versions/node/v8.9.4/bin/node" "/src/.nvm/versions/node/v8.9.4/bin/npm" "start"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error formio@1.28.0 start: `npm run version && node main.js`
22 error Exit status 1
23 error Failed at the formio@1.28.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by airarrazaval** [comment]
So after more debugging, the problem arises when creating a database using mongoose v5.0.16+.  The first time I run `npm start` it creates the database and then crashes.  If I do `npm start` a second time it works. If I delete the database and run `npm start` again, the crash repeats. Using mongoose v5.0.15 or lower do not present the problem.

**Comment by airarrazaval** [comment]
@travist @randallknutson This problem is also present in the formio/formio-server docker image.  As of today, formio/formio-server uses mongoose ^5.1.3 and cannot run using Mongo Atlas cluster.  Do you have any plans on fixing this?

**Comment by travist** [comment]
This is strange because we use the latest formio-server on our hosted environment with Mongo Atlas cluster and it works just fine without incident. Not sure what is causing this, but we will investigate.

**Comment by byKirby** [comment]
I've been having a similar issue as well getting the docker image (formio/formio-server) up and running with Mongo Atlas. Although the error I experienced was different. Here are my attempts:

Attempt 1 
MongoUrl used:
```
mongodb+srv://<user>:<password>@cluster0-abcd.mongodb.net/mydb?retryWrites=true
```
Docker command: 
```
docker run -itd -e "PORTAL_SECRET=portalsecret" -e "JWT_SECRET=jwtsecret" -e "DB_SECRET=dbsecret" -e "PROTOCOL=http" -e "MONGO=mongodb+srv://<user>:<password>@cluster0-abcd.mongodb.net/mydb?retryWrites=true" -e "MONGO_HIGH_AVAILABILITY=1" -p 3000:80 --name formio-server formio/formio-server
```
This resulted in the following error:
![image](https://user-images.githubusercontent.com/7763844/42952791-ce9946d4-8b3e-11e8-9356-81ab3541184b.png)

So I tried the same Docker command but removed the retryWrites option from the MongoUrl

Attempt 2
MongoUrl used:
```
mongodb+srv://<user>:<password>@cluster0-abcd.mongodb.net/mydb
```
SUCCESS! Though I suppose I'm losing/missing out on an important production feature?:
![image](https://user-images.githubusercontent.com/7763844/42953032-23190208-8b3f-11e8-94e7-7e613824d318.png)

Using the 3.4 Mongo connection URI always timed out for me, even with removing the retryWrites option. Docker logs always showed the container stopping/hanging here:
![image](https://user-images.githubusercontent.com/7763844/42953438-10ffc36c-8b40-11e8-90fd-834040fd250b.png)

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
