### ISSUE TITLE
Wrong Settings Key for SQL Action in default.json

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio#622]
When a SQL Action is executed it fetches the SQL server settings from `settings.databases` 

https://github.com/formio/formio/blob/b9d191c8de07dbc43f402779e8c11db9f3a9aa28/src/actions/SQLAction.js#L130-L137

Unfortunately, in the config template file, the settings property name is set to `database` 

https://github.com/formio/formio/blob/c72842b38fb36a304b3878594ac1e3d40f901f27/config/default.json#L31-L46

This causes the SQL action to throw an error on execution:

```
TypeError: Cannot read property 'mysql' of undefined
    at SQLAction.<anonymous> (/path/to/formio/src/actions/SQLAction.js:136:38)
    at Object.settings (/path/to/formio/src/util/hook.js:12:7)
    at SQLAction.resolve (/path/to/formio/src/actions/SQLAction.js:130:12)
    at /path/to/formio/src/actions/actions.js:226:18
    at /path/to/formio/node_modules/async/dist/async.js:3110:16
    at replenish (/path/to/formio/node_modules/async/dist/async.js:1011:17)
    at iterateeCallback (/path/to/formio/node_modules/async/dist/async.js:995:17)
    at /path/to/formio/node_modules/async/dist/async.js:969:16
    at /path/to/formio/src/actions/RoleAction.js:220:20
    at /path/to/formio/node_modules/mongoose/lib/model.js:4236:16
    at model.$__save.error (/path/to/formio/node_modules/mongoose/lib/model.js:381:7)
    at /path/to/formio/node_modules/kareem/index.js:315:21
    at next (/path/to/formio/node_modules/kareem/index.js:209:27)
    at Kareem.execPost (/path/to/formio/node_modules/kareem/index.js:217:3)
    at _cb (/path/to/formio/node_modules/kareem/index.js:307:15)
    at $__handleSave (/path/to/formio/node_modules/mongoose/lib/model.js:301:5)
```

To fix this, either change `config.json` settings database property to `databases` or change the property name in `SQLAction.js` to `settings.database[this.settings.type]`.

**Comment by ZenMasterJacob20011** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
