### ISSUE TITLE
SQL Action Before Handler not working

### ISSUE THREAD

**Issue by airarrazaval** [formio/formio#624]
when using SQL Action, if Before Handler is selected, the following error is thrown:

```
(node:9935) UnhandledPromiseRejectionWarning: Error: Callback was already called.
    at /path/to/formio/node_modules/async/dist/async.js:966:32
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:9935) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9935) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9935) UnhandledPromiseRejectionWarning: Error: Callback was already called.
    at /path/to/formio/node_modules/async/dist/async.js:966:32
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:9935) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

This makes impossible to use the before handler for (for example) getting submissions from SQL server as the application freezes (it does not crash the server, but user must refresh browser).

**Comment by ZenMasterJacob20011** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
