### ISSUE TITLE
npm start error (formio@1.33.5, Ubuntu 16.04.x)

### ISSUE THREAD

**Issue by bobslee** [formio/formio#645]
Hi,

I installed the formio stack on Ubuntu 16.04.x
- Mongodb (latest/stable)
- nodjes 8
- npm 6

When I start the server (npm start), it crashes with the following error.
Any suggestions please?

```
Initializing API Server.
 > Mongo connection established.
(node:3262) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
 > Serving application at http://localhost:8080
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at Function.listen (/home/###/formio-master/node_modules/express/lib/application.js:618:24)
    at start (/home/###/formio-master/server.js:67:21)
    at /home/###/formio-master/server.js:104:18
    at result (/home/###/formio-master/node_modules/mongodb/lib/utils.js:414:17)
    at session.endSession (/home/###/formio-master/node_modules/mongodb/lib/utils.js:401:11)
    at ClientSession.endSession (/home/###/formio-master/node_modules/mongodb-core/lib/sessions.js:129:41)
    at executeCallback (/home/###/formio-master/node_modules/mongodb/lib/utils.js:397:17)
    at handleCallback (/home/###/formio-master/node_modules/mongodb/lib/utils.js:128:55)
    at executeCommand (/home/###/formio-master/node_modules/mongodb/lib/operations/collection_ops.js:189:5)
    at handleCallback (/home/###/formio-master/node_modules/mongodb/lib/utils.js:128:55)
    at db.s.topology.command (/home/###/formio-master/node_modules/mongodb/lib/operations/db_ops.js:494:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! formio@1.33.5 start: `node main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the formio@1.33.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

The complete log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v8.11.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle formio@1.33.5~prestart: formio@1.33.5
6 info lifecycle formio@1.33.5~start: formio@1.33.5
7 verbose lifecycle formio@1.33.5~start: unsafe-perm in lifecycle true
8 verbose lifecycle formio@1.33.5~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/###/formio-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
9 verbose lifecycle formio@1.33.5~start: CWD: /home/###/formio-master
10 silly lifecycle formio@1.33.5~start: Args: [ '-c', 'node main.js' ]
11 silly lifecycle formio@1.33.5~start: Returned: code: 1  signal: null
12 info lifecycle formio@1.33.5~start: Failed to exec start script
13 verbose stack Error: formio@1.33.5 start: `node main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid formio@1.33.5
15 verbose cwd /home/###/formio-master
16 verbose Linux 4.15.0-33-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.11.4
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error formio@1.33.5 start: `node main.js`
22 error Exit status 1
23 error Failed at the formio@1.33.5 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by bobslee** [comment]
FYI... Just easily deployed "Form.io" on Ubuntu 18.04, without any issues.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
