### ISSUE TITLE
ReferenceError: self is not defined while running npm start

### ISSUE THREAD

**Issue by assadvirgo** [formio/formio#654]
Steps to reproduce
Installed fresh Ubuntu 18
Installed Node version 10
Installed MongDB
Cloned the repo
run npm install
run npm start

got following error

```
npm start

> formio@1.34.0 start /Users/assadmahmood/Projects/mylab/formio
> node main.js

/Users/assadmahmood/Projects/mylab/formio/node_modules/formiojs/node_modules/whatwg-fetch/dist/fetch.umd.js:8
    searchParams: 'URLSearchParams' in self,
                                       ^

ReferenceError: self is not defined
    at /Users/assadmahmood/Projects/mylab/formio/node_modules/formiojs/node_modules/whatwg-fetch/dist/fetch.umd.js:8:40
    at support.searchParams (/Users/assadmahmood/Projects/mylab/formio/node_modules/formiojs/node_modules/whatwg-fetch/dist/fetch.umd.js:2:66)
    at Object.<anonymous> (/Users/assadmahmood/Projects/mylab/formio/node_modules/formiojs/node_modules/whatwg-fetch/dist/fetch.umd.js:5:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/assadmahmood/Projects/mylab/formio/node_modules/formiojs/utils/utils.js:64:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! formio@1.34.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the formio@1.34.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/assadmahmood/.npm/_logs/2018-09-20T08_53_31_132Z-debug.log
```

Had exactly same issue on MacOS too.

**Comment by wag110894** [comment]
Hello Asssad,
This is William with the Form.io support team. Thanks for reaching out!
This was an issue with whatwg-fetch that broke importing formio.js on node. This should be fixed in the latest version of formio.js. 
Please let me know if have any further questions or concerns. 
Thanks,
William Gay 
Form.io Developer Support

**Comment by assadvirgo** [comment]
@wag110894 
Thanks for your response. The issue was resolved but now another issue poped up. Did following

1. Fresh cloned formio repo
2. npm install
3. npm start

got following error
```
/Users/assadmahmood/Projects/mylab/formio/src/export/exporters/CSVExporter.js:390
            ...column,
            ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/assadmahmood/Projects/mylab/formio/src/export/index.js:4:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

**Comment by assadvirgo** [comment]
@wag110894 nvm it was due eto node version. 
Thanks.
