### ISSUE TITLE
Cannot find module 'core-js/modules/es7.symbol.async-iterator'

### ISSUE THREAD

**Issue by kpturner** [formio/formio#669]
Cloned repo on a mac.
Ran `npm install`
Ran `npm start`

Result:
```
Error: Cannot find module 'core-js/modules/es7.symbol.async-iterator'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/formio/node_modules/formiojs/utils/index.js:8:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/formio/src/util/util.js:8:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by kpturner** [comment]
Fixed by using `nvm use 8` and installing again

**Comment by jdberkowitz** [comment]
Hi @kpturner I was wondering what version of node you were using when it threw this error? I'm having the same trouble with the migrate command throwing a similar error on v8.15.0 and the latest stable 10.15.0. I am attempting to migrate local csv data to the submission table in my project and it throws the error below.

Error: Cannot find module 'core-js/modules/es7.symbol.async-iterator'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Workstation\AppData\Roaming\nvm\v8.15.0\node_modules\formio-cli\node_modules\formiojs\utils\index.js:8:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by jdberkowitz** [comment]
Okay so I may have posted this a bit quickly but if anyone else has this issue I resolved it by : 
(On windows)
nvm to version 8.15 (Using nvm-windows)
navigate to your User\<user account>\AppData\Roaming\nvm\v8.15.0\node_modules\formio-cli
run "npm i core-js"
And that solved the missing dependency
