### ISSUE TITLE
Error for npm start, probably related to MongoDB

### ISSUE THREAD

**Issue by TheOtherRealm** [formio/formio#689]
When I try to start the app, I get this error.  After that, it just stalls at `DB is already locked for updating`.  Have tried the issue on both Linux and Windows using node 10 and the most recent stable MongoDB .
Not that familiar with Mongo, probably a simple fix.
```
E:\xampp\htdocs\otherrealm.org\form\formio\node_modules\mongodb\lib\utils.js:132
      throw err;
      ^

TypeError: schema.findOneAndUpdate(...).lean is not a function
    at E:\xampp\htdocs\otherrealm.org\form\formio\src\db\index.js:401:13
    at result (E:\xampp\htdocs\otherrealm.org\form\formio\node_modules\mongodb\lib\utils.js:414:17)
    at executeCallback (E:\xampp\htdocs\otherrealm.org\form\formio\node_modules\mongodb\lib\utils.js:406:9)
    at handleCallback (E:\xampp\htdocs\otherrealm.org\form\formio\node_modules\mongodb\lib\utils.js:128:55)
    at cursor.close (E:\xampp\htdocs\otherrealm.org\form\formio\node_modules\mongodb\lib\operations\cursor_ops.js:216:62)
    at handleCallback (E:\xampp\htdocs\otherrealm.org\form\formio\node_modules\mongodb\lib\utils.js:128:55)
    at completeClose (E:\xampp\htdocs\otherrealm.org\form\formio\node_modules\mongodb\lib\cursor.js:893:14)
    at _endSession (E:\xampp\htdocs\otherrealm.org\form\formio\node_modules\mongodb\lib\cursor.js:904:37)
    at Cursor._endSession (E:\xampp\htdocs\otherrealm.org\form\formio\node_modules\mongodb-core\lib\cursor.js:194:5)
    at Cursor._endSession (E:\xampp\htdocs\otherrealm.org\form\formio\node_modules\mongodb\lib\cursor.js:226:59)
    at Cursor.close (E:\xampp\htdocs\otherrealm.org\form\formio\node_modules\mongodb\lib\cursor.js:904:19)
    at cursor._next (E:\xampp\htdocs\otherrealm.org\form\formio\node_modules\mongodb\lib\operations\cursor_ops.js:216:23)
    at handleCallback (E:\xampp\htdocs\otherrealm.org\form\formio\node_modules\mongodb-core\lib\cursor.js:203:5)
    at _setCursorNotifiedImpl (E:\xampp\htdocs\otherrealm.org\form\formio\node_modules\mongodb-core\lib\cursor.js:561:38)
    at self._endSession (E:\xampp\htdocs\otherrealm.org\form\formio\node_modules\mongodb-core\lib\cursor.js:569:46)
    at ClientSession.endSession (E:\xampp\htdocs\otherrealm.org\form\formio\node_modules\mongodb-core\lib\sessions.js:129:41)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! formio@1.37.1 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the formio@1.37.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Someone\AppData\Roaming\npm-cache\_logs\2018-11-18T19_10_35_463Z-debug.log
```

**Comment by travist** [comment]
This is probably something I broke. I will get a fix in place asap.

**Comment by travist** [comment]
This is now fixed.

**Comment by TheOtherRealm** [comment]
Great, thanks.
