### ISSUE TITLE
Error: listen EACCES 0.0.0.0:3001 on Windows 10

### ISSUE THREAD

**Issue by evandropaes** [formio/formio#702]
I am having this issue when running Form.io on Windows 10. 

netstat -a -b does no show port 3001 being used. 

Any ideas on what's causing this exception?

Node --version = v10.13.0

> Serving the Form.io API Platform at http://localhost:3001
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:3001
    at Server.setupListenHandle [as _listen2] (net.js:1269:19)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at Function.listen (C:\Users\Evand\OneDrive\Development\AACD\formio\node_modules\express\lib\application.js:618:24)
    at C:\Users\Evand\OneDrive\Development\AACD\formio\main.js:7:16
    at _fulfilled (C:\Users\Evand\OneDrive\Development\AACD\formio\node_modules\q\q.js:854:54)
    at C:\Users\Evand\OneDrive\Development\AACD\formio\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Users\Evand\OneDrive\Development\AACD\formio\node_modules\q\q.js:816:13)
    at C:\Users\Evand\OneDrive\Development\AACD\formio\node_modules\q\q.js:624:44
    at runSingle (C:\Users\Evand\OneDrive\Development\AACD\formio\node_modules\q\q.js:137:13)
    at flush (C:\Users\Evand\OneDrive\Development\AACD\formio\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at emitErrorNT (net.js:1313:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by A-Pradeep** [comment]
Hey,
Have you re-checked any other process occupied the port 3001 before running the form.io application.
Even i ran form.io twice and i'm getting the same error.
![2018-12-05_10-26-36](https://user-images.githubusercontent.com/37439293/49490994-77888600-f878-11e8-83ef-fd46797f67ad.png)

This error occurs only when the port is already occupied. 

If the error still occurs , try to use another port (like 3002) and change in the `config.js`  in the `client/src/config.js`  inside APP_URL and API_URL to `http://localhost:port number`, and gulp build or else you can directly change the port in the `client/dist/config.js`.

**Comment by travist** [comment]
Thanks for your support @A-Pradeep.
