### ISSUE TITLE
[BUG] Dev Server Crash on invalid http message

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [formio/formio#858]
## Environment
Please provide as many details as you can:
- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 1.60.1
- Formio.js version: N/A
- Frontend framework: N/A
- Browser: N/A
- Browser version: N/A

## Steps to Reproduce
1. Send an invalid HTTP request, for example, set header Content-Type to application/json and with an invalid JSON body.
2. 
3. 

## Expected behavior
Some http response that effectively says bad json body or invalid request.
 
## Observed behavior
Crash with the following stack
```js
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:467:11)
    at ServerResponse.header (C:\Users\Michael Hobbs\WebstormProjects\formio\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (C:\Users\Michael Hobbs\WebstormProjects\formio\node_modules\express\lib\response.js:170:12)
    at LoginAction.resolve (C:\Users\Michael Hobbs\WebstormProjects\formio\src\actions\LoginAction.js:269:32)
    at C:\Users\Michael Hobbs\WebstormProjects\formio\src\actions\actions.js:225:22
    at Function.<anonymous> (C:\Users\Michael Hobbs\WebstormProjects\formio\node_modules\mongoose\lib\model.js:4638:16)
    at Function.<anonymous> (C:\Users\Michael Hobbs\WebstormProjects\formio\node_modules\mongoose\lib\utils.js:264:16)
    at _done (C:\Users\Michael Hobbs\WebstormProjects\formio\node_modules\mongoose\lib\model.js:3083:12)
    at C:\Users\Michael Hobbs\WebstormProjects\formio\node_modules\mongoose\lib\model.js:3092:18
    at callbackWrapper (C:\Users\Michael Hobbs\WebstormProjects\formio\node_modules\mongoose\lib\model.js:3048:11)
    at C:\Users\Michael Hobbs\WebstormProjects\formio\node_modules\mongoose\lib\model.js:4638:16
    at C:\Users\Michael Hobbs\WebstormProjects\formio\node_modules\mongoose\lib\utils.js:264:16
    at model.<anonymous> (C:\Users\Michael Hobbs\WebstormProjects\formio\node_modules\mongoose\lib\model.js:472:7)
    at C:\Users\Michael Hobbs\WebstormProjects\formio\node_modules\kareem\index.js:315:21
    at next (C:\Users\Michael Hobbs\WebstormProjects\formio\node_modules\kareem\index.js:209:27)
    at C:\Users\Michael Hobbs\WebstormProjects\formio\node_modules\kareem\index.js:182:9
    at C:\Users\Michael Hobbs\WebstormProjects\formio\node_modules\kareem\index.js:507:38
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
Emitted 'error' event at:
    at C:\Users\Michael Hobbs\WebstormProjects\formio\node_modules\mongoose\lib\model.js:4640:13
    at C:\Users\Michael Hobbs\WebstormProjects\formio\node_modules\mongoose\lib\utils.js:264:16
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
error Command failed with exit code 1.
```
## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
var loginResponse = fetch('http://192.168.1.6:3001/user/login', {
	method: 'POST', 
	headers: [['Content-Type', 'application/json']], 
	body: '{invalid'
})
```

**Comment by jhen1422** [comment]
@MichaelLeeHobbs 
Thank you for the report. We have added this to our backlog and I will have our dev team take a look at this.

**Comment by jhen1422** [comment]
@MichaelLeeHobbs After review, this is low on our priority . We would love a PR from the community to get this issue resolved .
