### ISSUE TITLE
[BUG] Error on setup

### ISSUE THREAD

**Issue by srinathganesh1** [formio/formio#886]
- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: master 

when i do docker-compose up formio

```
formio_1   | Which Github application would you like to install?
formio_1   |   1.) None
formio_1   |   2.) https://github.com/formio/formio-app-humanresources
formio_1   |   3.) https://github.com/formio/formio-app-servicetracker
formio_1   |   4.) https://github.com/formio/formio-app-todo
formio_1   |   5.) https://github.com/formio/formio-app-salesquote
formio_1   |   6.) https://github.com/formio/formio-app-basic
formio_1   | 
formio_1   | Or, you can provide a custom Github repository...
formio_1   | 
prompt: GitHub repository or selection?:  (1) Downloading client...
formio_1   | events.js:187
formio_1   |       throw er; // Unhandled 'error' event
formio_1   |       ^
formio_1   | 
formio_1   | Error: connect ETIMEDOUT 13.127.152.42:443
formio_1   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)
formio_1   | Emitted 'error' event on Request instance at:
formio_1   |     at Request.onRequestError (/app/node_modules/request/request.js:881:8)
formio_1   |     at ClientRequest.emit (events.js:210:5)
formio_1   |     at TLSSocket.socketErrorListener (_http_client.js:406:9)
formio_1   |     at TLSSocket.emit (events.js:210:5)
formio_1   |     at emitErrorNT (internal/streams/destroy.js:92:8)
formio_1   |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
formio_1   |     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
formio_1   |   errno: 'ETIMEDOUT',
formio_1   |   code: 'ETIMEDOUT',
formio_1   |   syscall: 'connect',
formio_1   |   address: '13.127.152.42',
formio_1   |   port: 443
formio_1   | }
formio_formio_1 exited with code 1
```

**Comment by travist** [comment]
We believe this is because the URL of the download is incorrect. There is a pull request to fix this.

https://github.com/formio/formio/pull/874

We will pull this in for our next release.

**Comment by srinathganesh1** [comment]
Thanks trying out the fix

**Comment by srinathganesh1** [comment]
I did the 2 line changes to my downloaded code and ran it
+ added some prints in install.js to print the URL being downloaded
```
prompt: GitHub repository or selection?:  (1) https://codeload.github.com/formio/formio-app-formio/zip/master
formio_1   | ####### download https://codeload.github.com/formio/formio-app-formio/zip/master ###########
formio_1   | Downloading client...
formio_1   | ########## https://codeload.github.com/formio/formio-app-formio/zip/master ###########3
formio_1   | events.js:187
formio_1   |       throw er; // Unhandled 'error' event
formio_1   |       ^
formio_1   | 
formio_1   | Error: connect ETIMEDOUT 13.127.152.42:443
formio_1   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)
formio_1   | Emitted 'error' event on Request instance at:
formio_1   |     at Request.onRequestError (/app/node_modules/request/request.js:881:8)
formio_1   |     at ClientRequest.emit (events.js:210:5)
formio_1   |     at TLSSocket.socketErrorListener (_http_client.js:406:9)
formio_1   |     at TLSSocket.emit (events.js:210:5)
formio_1   |     at emitErrorNT (internal/streams/destroy.js:92:8)
formio_1   |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
formio_1   |     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
formio_1   |   errno: 'ETIMEDOUT',
formio_1   |   code: 'ETIMEDOUT',
formio_1   |   syscall: 'connect',
formio_1   |   address: '13.127.152.42',
formio_1   |   port: 443
formio_1   | }
formio_formio_1 exited with code 1
```

THEN i did 

```
nslookup codeload.github.com
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   codeload.github.com
Address: 13.233.43.20
```

and to `docker-compose.yml` I did
```
extra_hosts:
      - "codeload.github.com:13.233.43.20"
```

```
prompt: GitHub repository or selection?:  (1) https://codeload.github.com/formio/formio-app-formio/zip/master
formio_1   | ####### download https://codeload.github.com/formio/formio-app-formio/zip/master ###########
formio_1   | Downloading client...
formio_1   | ########## https://codeload.github.com/formio/formio-app-formio/zip/master ###########3
formio_1   | events.js:187
formio_1   |       throw er; // Unhandled 'error' event
formio_1   |       ^
formio_1   | 
formio_1   | Error: connect ETIMEDOUT 13.233.43.20:443
formio_1   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14)
formio_1   | Emitted 'error' event on Request instance at:
formio_1   |     at Request.onRequestError (/app/node_modules/request/request.js:881:8)
formio_1   |     at ClientRequest.emit (events.js:210:5)
formio_1   |     at TLSSocket.socketErrorListener (_http_client.js:406:9)
formio_1   |     at TLSSocket.emit (events.js:210:5)
formio_1   |     at emitErrorNT (internal/streams/destroy.js:92:8)
formio_1   |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
formio_1   |     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
formio_1   |   errno: 'ETIMEDOUT',
formio_1   |   code: 'ETIMEDOUT',
formio_1   |   syscall: 'connect',
formio_1   |   address: '13.233.43.20',
formio_1   |   port: 443
formio_1   | }
formio_formio_1 exited with code 1
```

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
